### ISSUE TITLE
Implement/derive Canon for BidTree, Bid & Score structures.

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/dusk-blindbid#86]
This is needed in order to be able to write Smart Contracts through the Canon interface/bridge.

In particular, these implementations are required by the Bid Contract.

Also, the bid must contain the position in the tree to be able to implement `PoseidonLeaf`. This way, we need to update the hash and pre-image proof to contain also the `pos`

**Comment by vlopes11** [comment]
Seems the block height filtering should be performed from an iteration over the nth elements.

The `walk` method requires the base parameter to implement `Compound`, as in:
https://github.com/dusk-network/microkelvin/blob/main/src/branch.rs#L246

On `Kelvin`, we keep calling the `select` method from the `Branch` until we are depleted of nodes/leaves. On microkelvin, that is not possible, since `Branch` will not implement `Compound` and then it cannot be sent as parameter to `walk`

**Comment by vlopes11** [comment]
Description updated

**Comment by CPerezz** [comment]
Closed via #95
